# ndarray indexing guide

In [2]:
import numpy as np

Lets start with an assymetric matrix:

In [3]:
a  = np.array([[10, 5, 5, 5], [5, 10, 5, 5], [5, 5, 5, 5]])

In [4]:
a

array([[10,  5,  5,  5],
       [ 5, 10,  5,  5],
       [ 5,  5,  5,  5]])

what is the shape?

In [5]:
np.shape(a)

(3, 4)

i.e. 3 rows by 4 colmns. So how many if you want to loop through rows or cols?

In [6]:
np.shape(a)[0]

3

In [7]:
np.shape(a)[1]

4

In [8]:
for i in range (np.shape(a)[0]):
    print ('hello')

hello
hello
hello


Now comes the indexing. remember the **start:stop:step** scheme. Note that x[0,2] = x[0][2] though the second case is more inefficient a new temporary array is created after the first index that is subsequently indexed by 2.

In [9]:
a[0][0]

10

In [10]:
a[0,0]

10

First row:

In [11]:
a[0,:]

array([10,  5,  5,  5])

First col:

In [12]:
a[:,0]

array([10,  5,  5])

going through rows and printing columns

In [13]:
nrows = np.shape(a)[0]
ncols = np.shape(a)[1]
for i in range (ncols):
    print('Col {} is {}'.format(i, a[:,i]))

Col 0 is [10  5  5]
Col 1 is [ 5 10  5]
Col 2 is [5 5 5]
Col 3 is [5 5 5]


Sub matrix indexing:
rows 0 and 1, cols 1 and 2

In [14]:
a[0:2, 1:3]

array([[ 5,  5],
       [10,  5]])

In [15]:
b=np.array([1,2,3,4,1,2,3,4])

In [18]:
np.reshape(b, (2, 4))

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])