In [1]:
# Averging rows and columns in Numpy

In [2]:
import numpy

In [3]:
a = numpy.random.randint(10, size=(6,8))
print(a)

[[7 1 7 2 8 6 0 2]
 [8 7 0 7 7 4 9 3]
 [0 3 9 5 7 1 5 6]
 [9 5 5 0 0 2 5 6]
 [1 9 4 4 5 7 9 1]
 [7 8 3 3 2 1 4 6]]


In [4]:
b = numpy.sum(np.reshape(a, (3, 2, 8)), axis=1)
print(b)

[[15  8  7  9 15 10  9  5]
 [ 9  8 14  5  7  3 10 12]
 [ 8 17  7  7  7  8 13  7]]


In [5]:
c = numpy.sum(numpy.reshape(b, (3, 4, 2)), axis=2)
print(c)

[[23 16 25 14]
 [17 19 10 22]
 [25 14 15 20]]
