In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5,6,7, 8])

In [3]:
ba = b'asdasdad'

In [4]:
mytype = np.dtype((np.int16, {'Q':(np.int8,0), 'I':(np.int8,1)}))

In [5]:
np.zeros(1, dtype=mytype)

array([0], dtype=int16)

In [6]:
dt = np.dtype([('name', np.str_, 16), ('grades', np.float64, (2,))])

In [7]:
np.zeros(1, dtype=dt)

array([('', [0.0, 0.0])], 
      dtype=[('name', '<U16'), ('grades', '<f8', (2,))])

In [8]:
x = np.array([('Sarah', (8.0, 7.0)), ('John', (6.0, 7.0))], dtype=dt)

In [9]:
x[0]

('Sarah', [8.0, 7.0])

In [10]:
x[1]

('John', [6.0, 7.0])

In [11]:
dt.name

'void640'

In [12]:
ddd= np.dtype({'names': ['reserved1', 'validA', 'validP', 'validI', 'validQ', 'bins', 'reserved2', 'triggered', 'overLoad', 'lastFrame', 'ticks'], 
              'formats': [np.uint16, np.uint16, np.uint16, np.uint16, np.uint16, np.uint16, np.uint16, np.uint16,np.uint16, np.uint16, np.uint32]})

In [13]:
np.zeros(3, dtype=ddd)

array([(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
       (0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0), (0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)], 
      dtype=[('reserved1', '<u2'), ('validA', '<u2'), ('validP', '<u2'), ('validI', '<u2'), ('validQ', '<u2'), ('bins', '<u2'), ('reserved2', '<u2'), ('triggered', '<u2'), ('overLoad', '<u2'), ('lastFrame', '<u2'), ('ticks', '<u4')])

In [14]:
iq_type = np.dtype({'names': ['Q', 'I'],
                    'formats': [np.int16, np.int16]})

In [15]:
mytype = np.dtype([('hello',(iq_type,3)), 'bye',])

TypeError: data type not understood

In [16]:
np.zeros(2, dtype=mytype)

array([0, 0], dtype=int16)

In [17]:
mytype = np.dtype({'names': ['header', 'data'],
                  'formats': [(iq_type,1), (ddd,3)]})

In [18]:
iq_type.itemsize

4

In [19]:
a=np.zeros([1], dtype=iq_type)
a

array([(0, 0)], 
      dtype=[('Q', '<i2'), ('I', '<i2')])

In [20]:
a.astype('<c64')

array([b'0'], 
      dtype='|S1')

In [21]:
b=np.array([2, 3])
b

array([2, 3])

In [22]:
b.astype(iq_type)

array([(2, 2), (3, 3)], 
      dtype=[('Q', '<i2'), ('I', '<i2')])

In [23]:
a = np.arange(10, dtype=np.float16)
a

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.], dtype=float16)

In [24]:
a[1::2], a[::2]

(array([ 1.,  3.,  5.,  7.,  9.], dtype=float16),
 array([ 0.,  2.,  4.,  6.,  8.], dtype=float16))

In [25]:
header_size = 2
r = np.zeros(a.size - header_size, np.float16)
r

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.], dtype=float16)

In [26]:
r[0::2], r[1::2] = a[header_size + 1::2], a[header_size::2]
r

array([ 3.,  2.,  5.,  4.,  7.,  6.,  9.,  8.], dtype=float16)

In [27]:
r = r.astype(np.float32)
r

array([ 3.,  2.,  5.,  4.,  7.,  6.,  9.,  8.], dtype=float32)

In [28]:
r = r.view(np.complex64)
r

array([ 3.+2.j,  5.+4.j,  7.+6.j,  9.+8.j], dtype=complex64)

In [29]:
frame_data_type = np.dtype((iq_type, 1024))

In [30]:
x = np.random.rand(12,)
blah = 2
x

array([ 0.86926343,  0.13016122,  0.23648499,  0.08090459,  0.52767681,
        0.50118938,  0.17489246,  0.84359356,  0.87526184,  0.14459465,
        0.06457406,  0.74003434])

In [31]:
for i in range(int(len(x)/2)):
    print(i)
    print(x[blah*i:(i+1)*blah])

0
[ 0.86926343  0.13016122]
1
[ 0.23648499  0.08090459]
2
[ 0.52767681  0.50118938]
3
[ 0.17489246  0.84359356]
4
[ 0.87526184  0.14459465]
5
[ 0.06457406  0.74003434]


In [32]:
x.size

12

In [33]:
np.power(2,3)

8

In [37]:
a = np.arange(10, dtype=np.float16)
skip_annoying_header = 2
r = np.zeros(a.size - skip_annoying_header, np.float16)
r[0::2], r[1::2] = a[skip_annoying_header + 1::2], a[skip_annoying_header::2]
r = r.astype(np.float32)
r = r.view(np.complex64)

In [40]:
r[:,::-1].copy().view(np.complex64)

IndexError: too many indices for array

In [ ]:
a = np.arange(10, dtype=np.float16)
skip_annoying_header = 2
r = np.zeros(a.size - skip_annoying_header, np.float16)
r[0::2], r[1::2] = a[skip_annoying_header + 1::2], a[skip_annoying_header::2]
r = r.astype(np.float32)
r = r.view(np.complex64)